// This file was generated by github.com/vektah/gqlgen, DO NOT EDIT

package gqlserver

type Blog struct {
	ID       string   `json:"id"`
	Title    string   `json:"title"`
	Body     string   `json:"body"`
	Category Category `json:"category"`
}
type Category struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
type User struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Blogs []Blog `json:"blogs"`
}
